baseURL = "/"
languageCode = "en-us"
title = "Bureaucrat"
theme = "casper3"


[params]
facebook = "https://facebook.com"
twitter = "https:/"

[[Scratch.Get]]
background = "https://images.unsplash.com/photo-1598077850782-ce3589f9c9e5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"

[[menu.main]]
name = "About"
url = "/about"
weight = 3
[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1